runtime: python39
instance_class: F2
entrypoint: uvicorn app.main:app --host=0.0.0.0 --port=8080
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms
  max_instances: 1
runtime_config:
  python_version: 3.9
